services:
  # app:
  #   build: .
  #   command: yarn dev
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3333:3333'
  #   volumes:
  #     - .:/usr/app
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_NAME=${DB_NAME}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '${DB_PORT}:5432'